name: Library

on: [pull_request]

env:
  RUST_LOG: "0"

jobs:
  build:
    name: standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn install
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          target: wasm32-unknown-unknown
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy --all --no-deps
      - name: Run test ganache instance
        run: make test-server &
      - name: Wait a while for test server
        run: sleep 2
      - name: Fund the MPC account
        run: make fund-mpc-account
      - name: Run cargo test
        run: cargo test --all
      - name: Run cargo doc
        run: cargo doc --all --no-deps
      - name: Run build
        run: cargo build --all
      - name: Run build for wasm32
        run: cargo build --all --target wasm32-unknown-unknown --exclude web3-test-helpers
